### ISSUE TITLE
有如何新增第三方c库的教程吗？

### ISSUE THREAD

**Issue by sue602** [lolo1208/unity3d-lolo#2]
如 sproto , lua-crypt

**Comment by lolo1208** [comment]
在 tolua runtime 中添加对应的 c 库，再编译出 [/Assets/Plugins](https://github.com/lolo1208/unity3d-lolo/tree/master/Assets/Plugins) 中各平台的 tolua 库，并替换。

另外还需在项目 [LuaDll.cs](https://github.com/lolo1208/unity3d-lolo/blob/master/Assets/Framework/ToLua/Core/LuaDLL.cs#L218) 与 [LuaManager.cs](https://github.com/lolo1208/unity3d-lolo/blob/master/Assets/Framework/ShibaInu/Core/LuaManager.cs#L50) 中添加对应的 C# 代码。

[tolua runtime](https://github.com/topameng/tolua_runtime)
[参考文章](https://www.jianshu.com/p/3c5db3e6b4e7)
