### ISSUE TITLE
导入报错哦大佬，

### ISSUE THREAD

**Issue by easyboy3** [lolo1208/unity3d-lolo#3]
Assets\Framework\ToLua\Source\Generate\System_DateTimeWrap.cs(679,39): error CS0306: The type 'ReadOnlySpan<char>' may not be used as a type argument

Assets\Framework\ToLua\Source\Generate\UnityEngine_MaterialWrap.cs(584,23): error CS1615: Argument 1 may not be passed with the 'ref' keyword

**Comment by lolo1208** [comment]
你的环境好像与我不一样呀，能说下你的Unity版本号吗？

这类错误一般在生成 Wraps 时屏蔽掉对应的函数或属性就能解决。
[/Assets/Framework/App/Core/ToLuaExtend.cs](https://github.com/lolo1208/unity3d-lolo/blob/master/Assets/Framework/App/Core/ToLuaExtend.cs#L18)
在这添加要排除的内容，然后点击菜单项 `ShibaInu` -> `Generate Lua Wraps`

**Comment by easyboy3** [comment]
你好我用的是2021.3.5f1打开的，打开自动生成wrap，确定后就报错了，除了System_DateTimeWrap这个我没遇到之外，其他的应该是“ref”导出会有问题，这种我可能放到baseType就行。另外我想请问的是，UniTask是不是不能导出在lua使用的，因为我没找到相关的lua异步加载资源的同步写法，，都是异步+回调callback的写法处理起来比较难顶。

**Comment by lolo1208** [comment]
UniTask 是 C# 用的，Lua 用不了！并且 Lua 本身的协程由于跨语言不稳定，也已经被我禁用了。
[lua coroutine](https://github.com/lolo1208/unity3d-lolo/blob/master/Assets/Framework/ShibaInu/Lua/Core/initialize.lua#L109)

**Comment by easyboy3** [comment]
那岂不是说如果用lua做热更，而且要异步加载资源的话，只能是写回调了？这样对于需要边玩边下，或者用到才加载的资源，那可能会经常有残留，或者清理不干净（正在异步生成中）的情况。会维护得很费力了。

**Comment by lolo1208** [comment]
可以用 [ResManager.UnloadAll()](https://github.com/lolo1208/unity3d-lolo/blob/master/Assets/Framework/ShibaInu/Core/ResManager.cs#L718) 来卸载全部资源，你可以参考 [Relaunch()](https://github.com/lolo1208/unity3d-lolo/blob/566c9bfed3598ff7adb92658886bfa76853cfb6c/Assets/Framework/ShibaInu/Core/Launcher.cs#L80) 的逻辑。

**Comment by lolo1208** [comment]
已升级到 Unity 2021
