### ISSUE TITLE
有更新lua代码的范例吗？麻烦大佬指点。

### ISSUE THREAD

**Issue by sue602** [lolo1208/unity3d-lolo#4]
如题

**Comment by lolo1208** [comment]
你可以查看介绍页 [Build](https://github.com/lolo1208/unity3d-lolo#build) 部分，了解项目打包方式。
例如，使用脚本：
`node Tools/lib/build.js -i 0 -v 1.2.3 -p %proj_name% -t ios -f %proj_path% -z %zip_or_dir_path%`
生成所有资源（包括lua）的 zip 包，可根据 zip 文件内容生成差异包（动更包），部署在服务器上。
游戏内可通过 [UpdateManager.cs](https://github.com/lolo1208/unity3d-lolo/blob/master/Assets/Framework/ShibaInu/Core/UpdateManager.cs) 与 [HttpDownload.lua](https://github.com/lolo1208/unity3d-lolo/blob/master/Assets/Framework/ShibaInu/Lua/Net/HttpDownload.lua) 来实现动更逻辑。
动更完成后，可调用 lua 全局函数 [Relaunch()](https://github.com/lolo1208/unity3d-lolo/blob/master/Assets/Lua/Module/Core/extends.lua#L178) 重启游戏。

**Comment by sue602** [comment]
感谢
