### ISSUE TITLE
Intellij IDE can not recognize Wrapper class

### ISSUE THREAD

**Issue by kietgula** [lolo1208/unity3d-lolo#5]
![image](https://user-images.githubusercontent.com/61832885/226787551-26bcc8e5-ee4b-42d8-97b4-1bd6def6058d.png)

**Comment by lolo1208** [comment]
https://github.com/lolo1208/unity3d-lolo#-%E5%AE%89%E8%A3%85-emmylua-%E6%8F%92%E4%BB%B6

安装 emmylua 插件，添加 Assets/LuaAPI 目录。
