### ISSUE TITLE
大佬你好，我想请问一下，我在打包的过程中遇到一个问题，不太清楚哪里可以对其可以进行修改，麻烦大佬看一下

### ISSUE THREAD

**Issue by jlk1997** [lolo1208/unity3d-lolo#6]
![image](https://github.com/user-attachments/assets/18922488-a82d-4f7b-bf20-cd0f9595355a)
出现这个错误。是路径错误吗？我看路径中有/和\同时存在，可是查阅了所有的bat与config，里面都是/
还是说有其他问题呢，麻烦大佬看一下

**Comment by jlk1997** [comment]
![image](https://github.com/user-attachments/assets/9e41cfce-8bfc-4990-b67d-94c2b2c2c1c5)
通宵测试排除以下问题：
1：路径应该是正确
2：与Unity版本无关
3：修改了-develop参数为false，还是不行
请大佬指教，感谢

**Comment by lolo1208** [comment]
排查方向错了，这是生成AndroidStudio报错，unity场景和AB包都已经生产完毕了，不会是Unity路径或版本的错误。

你可以在打包进度与日志页面左侧切换到【Unity运行日志】，查看具体报错信息。

**Comment by jlk1997** [comment]
大佬，我成功导出了安卓项目到Android Studio中，目前使用的gradle是7.5.1，JDK是corretto-11，（也测试了其他各个jdk版本）
但都会在导出apk时出现PermissionActivity.java文件的报错
![image](https://github.com/user-attachments/assets/0b2d3613-07cd-4823-b6e4-660af954b69e)
每次单纯build项目的时候是能成功的，但是在导出apk时，无论替换哪个jdk版本，这个java文件的错误始终无法解决，请问大佬有人遇到过这个问题吗，大概率做什么能解决并成功打包apk呢？
感谢

**Comment by jlk1997** [comment]
该文件位于目录如下：
![image](https://github.com/user-attachments/assets/edff035a-1c11-4268-a80e-6e3c4b17525f)

**Comment by jlk1997** [comment]
解决啦，谢谢大佬！把这个java文件全都注释了就好了
